import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeadNav from "./HeadNav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="h-screen">
          <div className="grid h-full w-full grid-cols-2 gap-4">
            <div className="...">{/* <HeadNav /> */}NavBar</div>
            <div className="...">Profile</div>
            <div className="col-span-2 flex justify-center items-center">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
